const videoFeed=document.querySelector('.content');
const videoPosts=[
 {title:'Stäbe, Zauberinnen und das Licht der Versuchung',time:'Gerade eben · Magischer Marktplatz · 18+',copy:'Auf dem Marktplatz gilt: Ein eindrucksvoller Stab allein macht noch keinen großen Zauber. Erst wenn eine selbstbewusste Zauberin den richtigen Winkel wählt, warmes Licht über die Roben streicht und beide vorher wissen, welcher Funke überspringen darf, beginnt die wirklich reizvolle Magie. Zu hartes Licht enthüllt jeden billigen Taschenspielertrick, zu wenig Licht lässt selbst den prächtigsten Stab schüchtern wirken – und wer ungefragt damit herumwedelt, bekommt höchstens Hausverbot beim Hexenrat. Also: Stab polieren, Zauberin fragen, Kerzen dimmen und die Magie mit einem klaren Ja entzünden. ✨',src:'assets/magischer-marktplatz.mp4'},
 {title:'Ihr Blick ist der erste Zauber',time:'Neu · D4Serve Waldgeflüster',copy:'Sie wartet dort, wo der Waldweg schmaler und die Blicke länger werden. Ein Lächeln, ein freches Zwinkern – und schon stellt sich nur noch die Frage, ob du ihrer Spur bis zum Salon folgen möchtest. Der Mantel bleibt vorerst geschlossen; Fantasie und klare Einladung übernehmen den Rest.',src:'assets/nachtwald-begegnung.mp4',poster:'assets/silbermagierin-wald.png'},
 {title:'Zwei Tränke, eine eindeutige Einladung',time:'Neu · D4Serve Ausschank',copy:'Zwei Gläser stehen bereit, doch serviert wird erst nach Blickkontakt und einem ausgesprochenen Wunsch. Sie kennt die richtige Mischung aus süßem Versprechen, prickelnder Spannung und jener höflichen Zurückhaltung, die Lust auf den nächsten Schluck macht.',src:'assets/silbermagie.mp4'},
 {title:'Der Zauberer-Tanz',time:'Video · Tanzritual',copy:'Ein Schritt nach vorn, ein Blick zurück und genau genug Hüftschwung, damit selbst der steifste Zauberstab seinen Takt findet. Ton an und mittanzen.',src:'assets/zauberer-tanz.mp4'},
 {title:'D4Serve – der verborgene Dienst',time:'Video · D4Serve',copy:'Was geschieht, wenn der Wizzard nicht nur zaubert, sondern serviert? Ein neuer Blick hinter die Kulissen von D4Serve – aufmerksam, diskret und mit einer Prise Magie.',src:'assets/d4serve.mp4'},
 {title:'Wenn der Zauberer zu glühen beginnt',time:'Neu · Zauberer-Moment',copy:'Ein warmer Schein, ein ruhiger Blick und plötzlich liegt Spannung in der Luft. Dieser Zauber wirkt ohne Eile: erst neugierig annähern, die Magie aufbauen und gemeinsam entscheiden, wie intensiv das Leuchten werden darf.',src:'assets/zauberer-gluehen.mp4'},
 {title:'D4Serve – ein Blick genügt',time:'Neu · D4Serve-Einladung',copy:'Er kommt näher, zwinkert und lässt keinen Zweifel daran, dass der Abend interessant wird. D4Serve bedeutet Aufmerksamkeit mit Haltung: Wünsche werden ausgesprochen, Grenzen respektiert und jedes Spiel beginnt mit einem eindeutigen Ja.',src:'assets/d4serve-zwinkern.mp4'},
 {title:'Zauberer nach Einbruch der Nacht',time:'Neu · Nachtzauber',copy:'Wenn die Türen des Salons geschlossen sind, beginnt die Stunde des Zauberers. Gedämpftes Licht, sorgfältig gewählte Rituale und ein Wizzard, der genau zuhört – für volljährige Gäste, die ihre Regeln vorher gemeinsam festlegen.',src:'assets/d4serve-nachtzauber.mp4'}
];
const renderVideoPost=video=>`<article class="post video-post"><header class="post-head"><div class="post-avatar">OW</div><div><b>Only Wizzard <span class="verified">✓</span></b><span>${video.time}</span></div></header><div class="post-copy"><p><b>${video.title}</b> ${video.copy}</p></div><video controls playsinline preload="metadata"${video.poster?` poster="${video.poster}"`:''}><source src="${video.src}" type="video/mp4">Dein Browser unterstützt dieses Video nicht.</video><footer class="post-actions"><button class="like">♡ <span>219</span></button><button>○ <span>48</span></button><button>↗</button><button class="bookmark">⌑</button></footer></article>`;
videoFeed.insertAdjacentHTML('afterbegin',renderVideoPost(videoPosts[0]));
const seductivePosts=[
 {title:'Stabpflege mit Haltung',time:'Gerade eben · Werkstattgeflüster · 18+',copy:'Eine erfahrene Zauberin weiß: Länge beeindruckt höchstens beim ersten Blick – entscheidend sind Balance, Fingerspitzengefühl und die Kunst, den Stab nicht gleich beim ersten Funken aus der Hand zu geben. In dieser Privatvorführung wird langsam poliert, aufmerksam geprüft und erst dann gezaubert, wenn das Gegenüber ausdrücklich mehr Magie verlangt. Der Kater schaut nur deshalb so streng, weil wieder niemand die Werkbank abgewischt hat.',src:'assets/stabpflege-mit-haltung.png',alt:'Erwachsene Zauberin mit kunstvollem Zauberstab in einer luxuriösen Kerzenwerkstatt'},
 {title:'Das Mitternachtselixier: erst nippen, dann knistern',time:'Neu · Alchemistische Versuchung · 18+',copy:'Zwei Zauberinnen, ein dampfender Kelch und eine Rezeptur, bei der selbst der Mond rote Ohren bekäme. Getrunken wird Schluck für Schluck: erst Blickkontakt, dann ein freches Lächeln und schließlich die Frage, wer heute eigentlich wen verzaubert. Nebenwirkungen können warme Wangen, lockere Robenkragen und der dringende Wunsch nach einer sehr privaten Nachbesprechung sein.',src:'assets/mitternachtselixier.png',alt:'Zwei erwachsene Zauberinnen bei einer nächtlichen Verkostung eines violett leuchtenden Elixiers'},
 {title:'Privatlektion im kontrollierten Funkenflug',time:'Neu · Nachsitzen in der Bibliothek · 18+',copy:'Wenn die Bibliothek schließt, beginnt der Unterricht für Fortgeschrittene: Sie legt den Stab auf den Samt, er erklärt mit bemerkenswert tiefer Stimme, wie man die Spannung hält, und plötzlich glüht mehr als nur die Spitze. Die wichtigste Prüfungsfrage lautet trotzdem nicht „Wie oft?“, sondern „Darf ich?“. Wer richtig antwortet, darf bis zum nächsten Funken sitzen bleiben.',src:'assets/privatlektion-funkenflug.png',alt:'Erwachsene Zauberin und erwachsener Zauberer bei einer nächtlichen Privatlektion in einer Schlossbibliothek'}
];
const renderSeductivePost=item=>`<article class="post newest-seductive-post"><header class="post-head"><div class="post-avatar seductive-avatar">18+</div><div><b>Only Wizzard · Nachtakademie <span class="verified">✓</span></b><span>${item.time}</span></div><button>•••</button></header><div class="post-copy"><p><b>${item.title}:</b> ${item.copy}</p></div><img class="seductive-photo" src="${item.src}" alt="${item.alt}" loading="eager"><div class="seductive-note">Nur für Erwachsene · einvernehmlich · Magie nur auf Einladung</div><footer class="post-actions"><button class="like">♡ <span>427</span></button><button>○ <span>103</span></button><button>↗</button><button class="bookmark">⌑</button></footer></article>`;
videoFeed.insertAdjacentHTML('afterbegin',seductivePosts.map(renderSeductivePost).join(''));
const featuredVideoHtml=videoPosts.slice(1,3).map(renderVideoPost).join('');
const latestFeatures=document.querySelectorAll('.intimacy-post');
const latestFeature=latestFeatures[latestFeatures.length-1];
latestFeature?latestFeature.insertAdjacentHTML('afterend',featuredVideoHtml):videoFeed.insertAdjacentHTML('afterbegin',featuredVideoHtml);
videoFeed.insertAdjacentHTML('beforeend',videoPosts.slice(3).map(renderVideoPost).join(''));

document.querySelectorAll('.content .post').forEach((post,index)=>{
  const control=document.createElement('section');control.className='comments-control';
  control.innerHTML=`<button class="comments-toggle" aria-expanded="false"><span>○</span> KOMMENTARE ÖFFNEN <b>⌄</b></button><div class="comments-panel" hidden><p>Kommentare werden über GitHub Discussions gespeichert. Zum Schreiben ist eine kostenlose GitHub-Anmeldung erforderlich.</p><div class="giscus-host"></div></div>`;
  post.appendChild(control);
  const toggle=control.querySelector('.comments-toggle');const panel=control.querySelector('.comments-panel');
  toggle.addEventListener('click',()=>{const opening=panel.hidden;panel.hidden=!opening;toggle.setAttribute('aria-expanded',String(opening));toggle.innerHTML=opening?'<span>○</span> KOMMENTARE SCHLIESSEN <b>⌃</b>':'<span>○</span> KOMMENTARE ÖFFNEN <b>⌄</b>';if(opening&&!panel.dataset.loaded){const script=document.createElement('script');script.src='https://giscus.app/client.js';script.async=true;script.crossOrigin='anonymous';script.setAttribute('data-repo','d4wizzard/only-wizzard');script.setAttribute('data-repo-id','R_kgDOUHhKsg');script.setAttribute('data-category','General');script.setAttribute('data-category-id','DIC_kwDOUHhKss4DEaR2');script.setAttribute('data-mapping','specific');script.setAttribute('data-term',`Only Wizzard Beitrag ${index+1}`);script.setAttribute('data-strict','1');script.setAttribute('data-reactions-enabled','1');script.setAttribute('data-emit-metadata','0');script.setAttribute('data-input-position','top');script.setAttribute('data-theme',document.documentElement.dataset.theme==='dark'?'dark_dimmed':'light');script.setAttribute('data-lang','de');control.querySelector('.giscus-host').appendChild(script);panel.dataset.loaded='true'}})
});

document.querySelectorAll('.video-post .like,.newest-seductive-post .like').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('liked');button.firstChild.textContent=button.classList.contains('liked')?'♥ ':'♡ ';const count=button.querySelector('span');count.textContent=Number(count.textContent)+(button.classList.contains('liked')?1:-1)}));
