const videoFeed=document.querySelector('.content');
[
 {title:'Der Zauberer-Tanz',time:'Video · Tanzritual',copy:'Ein Schritt nach vorn, ein Blick zurück und genau genug Hüftschwung, damit selbst der steifste Zauberstab seinen Takt findet. Ton an und mittanzen.',src:'assets/zauberer-tanz.mp4'},
 {title:'D4Serve – der verborgene Dienst',time:'Video · D4Serve',copy:'Was geschieht, wenn der Wizzard nicht nur zaubert, sondern serviert? Ein neuer Blick hinter die Kulissen von D4Serve – aufmerksam, diskret und mit einer Prise Magie.',src:'assets/d4serve.mp4'}
].forEach(video=>videoFeed.insertAdjacentHTML('beforeend',`<article class="post video-post"><header class="post-head"><div class="post-avatar">OW</div><div><b>Only Wizzard <span class="verified">✓</span></b><span>${video.time}</span></div></header><div class="post-copy"><p><b>${video.title}</b> ${video.copy}</p></div><video controls playsinline preload="metadata"><source src="${video.src}" type="video/mp4">Dein Browser unterstützt dieses Video nicht.</video><footer class="post-actions"><button class="like">♡ <span>219</span></button><button>○ <span>48</span></button><button>↗</button><button class="bookmark">⌑</button></footer></article>`));

document.querySelectorAll('.content .post').forEach((post,index)=>{
  const control=document.createElement('section');control.className='comments-control';
  control.innerHTML=`<button class="comments-toggle" aria-expanded="false"><span>○</span> KOMMENTARE ÖFFNEN <b>⌄</b></button><div class="comments-panel" hidden><p>Kommentare werden über GitHub Discussions gespeichert. Zum Schreiben ist eine kostenlose GitHub-Anmeldung erforderlich.</p><div class="giscus-host"></div></div>`;
  post.appendChild(control);
  const toggle=control.querySelector('.comments-toggle');const panel=control.querySelector('.comments-panel');
  toggle.addEventListener('click',()=>{const opening=panel.hidden;panel.hidden=!opening;toggle.setAttribute('aria-expanded',String(opening));toggle.innerHTML=opening?'<span>○</span> KOMMENTARE SCHLIESSEN <b>⌃</b>':'<span>○</span> KOMMENTARE ÖFFNEN <b>⌄</b>';if(opening&&!panel.dataset.loaded){const script=document.createElement('script');script.src='https://giscus.app/client.js';script.async=true;script.crossOrigin='anonymous';script.setAttribute('data-repo','d4wizzard/only-wizzard');script.setAttribute('data-repo-id','R_kgDOUHhKsg');script.setAttribute('data-category','General');script.setAttribute('data-category-id','DIC_kwDOUHhKss4DEaR2');script.setAttribute('data-mapping','specific');script.setAttribute('data-term',`Only Wizzard Beitrag ${index+1}`);script.setAttribute('data-strict','1');script.setAttribute('data-reactions-enabled','1');script.setAttribute('data-emit-metadata','0');script.setAttribute('data-input-position','top');script.setAttribute('data-theme','light');script.setAttribute('data-lang','de');control.querySelector('.giscus-host').appendChild(script);panel.dataset.loaded='true'}})
});

document.querySelectorAll('.video-post .like').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('liked');button.firstChild.textContent=button.classList.contains('liked')?'♥ ':'♡ ';const count=button.querySelector('span');count.textContent=Number(count.textContent)+(button.classList.contains('liked')?1:-1)}));
