const d4serveFeed=document.querySelector('.content');
[
 {title:'Die Herrin des Mitternachtssalons',time:'D4Serve · Mitternacht',copy:'Schwarze Spitze, rubinroter Blick und eine Einladung, die keine Fragen offenlässt. Sie bestimmt das Tempo des Abends – du entscheidest, ob du ihrer diskreten Führung folgen möchtest. Nur für volljährige Gäste und immer nach klarer Absprache.',src:'assets/d4serve-mitternacht.png',alt:'Erwachsene Frau in schwarz-roter Gothic-Kleidung in einem Salon bei Kerzenlicht'},
 {title:'Ein Glas, ein Blick, eine Einladung',time:'D4Serve · Private Audienz',copy:'Der Platz gegenüber ist noch frei. Ein Glas dunkler Salontrank, ein herausforderndes Lächeln und genug Zeit, um Wünsche und Grenzen leise zu besprechen. Wer die Einladung annimmt, sollte gute Manieren und ein deutliches Ja mitbringen.',src:'assets/d4serve-einladung.png',alt:'Erwachsene Frau in einem gotischen Sessel mit einem Glas in der Hand'},
 {title:'Ihre Stimme im Regen',time:'D4Serve · Flüsterdienst',copy:'Kopfhörer auf, Außenwelt aus. Ihre Stimme führt dich durch ein privates Gedankenritual aus Nähe, Erwartung und kleinen Aufgaben. Du bestimmst Lautstärke und Stoppwort – sie kümmert sich um das Kribbeln dazwischen.',src:'assets/d4serve-stimme-im-regen.png',alt:'Erwachsene dunkelhaarige Frau mit Kopfhörern an einem verregneten Fenster'},
 {title:'Stiefel, Spitze und klare Regeln',time:'D4Serve · Garderobenmagie',copy:'Manche Auftritte beginnen mit einem Blick auf die hohen Stiefel und enden mit der höflichen Frage, wer heute führen darf. Bei D4Serve gehören Haltung, gepflegtes Leder und vorher vereinbarte Spielregeln zum guten Ton.',src:'assets/d4serve-stiefelritual.png',alt:'Erwachsene Gothic-Frau mit hohen schwarzen Schnürstiefeln in einem Kerzensalon'},
 {title:'D4Serve für zwei',time:'D4Serve · Begegnung',copy:'Zwei Gestalten, eine regennasse Nacht und diese Nähe, bei der selbst kalte Straßen plötzlich warm wirken. Unser Paarritual verbindet Blickkontakt, langsame Berührungen und ehrliche Absprachen – ohne Eile und ohne unausgesprochene Erwartungen.',src:'assets/d4serve-zu-zweit.png',alt:'Erwachsenes Gothic-Paar in inniger Umarmung auf einer regennassen Straße'},
 {title:'Der rote Salon',time:'D4Serve · Späte Stunde',copy:'Im roten Salon wird nicht geraten, sondern gefragt. Wie nah darf der Wizzard kommen, welche Berührung ist willkommen und welches Wort löst jeden Bann sofort? Erst wenn beides stimmt – die Spannung und das Vertrauen – beginnt die eigentliche Magie.',src:'assets/d4serve-roter-salon.png',alt:'Erwachsenes Gothic-Paar in einer intimen Pose in einem dunklen Salon'}
].forEach(item=>d4serveFeed.insertAdjacentHTML('beforeend',`<article class="post d4serve-photo-post"><header class="post-head"><div class="post-avatar">D4</div><div><b>D4Serve <span class="verified">✓</span></b><span>${item.time}</span></div><button>•••</button></header><div class="post-copy"><p><b>${item.title}:</b> ${item.copy}</p></div><img class="d4serve-photo" src="${item.src}" alt="${item.alt}" loading="lazy"><footer class="post-actions"><button class="like">♡ <span>284</span></button><button>○ <span>61</span></button><button>↗</button><button class="bookmark">⌑</button></footer></article>`));

