const newestFeed=document.querySelector('.content');
Object.assign(articles,{
 bedchamberPact:{kicker:'Schlafgemach-Etikette · 18+',title:'Der Pakt vor der Burgtür',intro:'Bevor zwei Zaubernde das Schlafgemach betreten, lohnt ein kurzer Pakt. Er muss nicht auf Pergament stehen – verständlich, freiwillig und jederzeit änderbar sollte er trotzdem sein.',sections:[['Was heute gewünscht ist','Beide besprechen konkret, welche Nähe willkommen ist und was nicht. Zustimmung zu Küssen, Rollenspiel oder Fesselung umfasst keine weiteren sexuellen Handlungen. Jede neue Stufe erhält ihr eigenes Ja; ein früheres Ja kann jederzeit zurückgenommen werden.'],['Schutz und Gesundheit','Verhütung, Schutzbarrieren, STI-Status und relevante gesundheitliche Themen werden ohne Spott besprochen. Kondome und andere Barrieren werden passend ausgewählt, korrekt gelagert und nach Herstellerangaben verwendet. Bardenlieder ersetzen keine Gebrauchsanleitung.'],['Privatsphäre','Fotos, Videos oder das Weitererzählen intimer Details benötigen eine eigene Zustimmung. Ein geschlossener Burgturm ist keine automatische Drehgenehmigung. Geräte bleiben weg, sofern nichts anderes ausdrücklich vereinbart wurde.'],['Danach','Wasser, Toilettengang, Reinigung, Ruhe und ein kurzer Check-in gehören zur guten Schlafgemach-Etikette. Schmerzen, Verletzungen oder starke emotionale Reaktionen werden ernst genommen und bei Bedarf medizinisch oder professionell abgeklärt.']]},
 castlePetplay:{kicker:'Petplay · Schlossmenagerie',title:'Der Schlosswolf bleibt ein erwachsener Mensch',intro:'Petplay ist ein freiwilliges Rollenspiel zwischen Erwachsenen. Ohren, Glocke und verspielte Aufgaben können den Alltag herrlich weit weg rücken – echte Tiere und echte Besitzrechte bleiben draußen.',sections:[['Rolle und Bedeutung','Vorher wird geklärt, welches Tierbild, welche Namen, Geräusche und Verhaltensweisen Spaß machen. Niemand muss sprechen, krabbeln, essen oder Zubehör tragen, nur weil es zu einem Klischee gehört. Die Rolle endet am vereinbarten Signal.'],['Petspace und Signale','Wer tief in der Rolle ist, kann weniger verbal reagieren. Deshalb werden einfache Handzeichen, Ampelfarben oder ein Gegenstand zum Fallenlassen vereinbart. Der führende Part prüft regelmäßig Wohlbefinden, Orientierung und körperliche Belastung.'],['Zubehör','Ohren, Schweif und dekoratives Halsband müssen bequem, sauber und schnell abnehmbar sein. Am Halsband wird nicht gezogen, wenn es nicht ausdrücklich dafür konstruiert und die Anwendung fachkundig vereinbart ist. Atmung, Hals und Wirbelsäule bleiben geschützt.'],['Zurück zum Menschen','Die Rolle wird hörbar beendet. Wasser, Wärme, normale Ansprache und die Frage nach Nähe oder Abstand helfen beim Zurückkehren. Lob darf reichlich sein; Hundekekse sollten hingegen nur serviert werden, wenn sie tatsächlich für Menschen gedacht sind.']]},
 serviceRoles:{kicker:'BDSM · Höfischer Dienst',title:'Dienen mit Haltung – führen mit Verantwortung',intro:'Ein Tablett, ein Blick und eine höfliche Verbeugung können erstaunlich viel Spannung erzeugen. Ein Dienst-Rollenspiel bleibt jedoch eine freiwillige Vereinbarung, kein mittelalterlicher Arbeitsvertrag auf Lebenszeit.',sections:[['Aufgabenmenü','Beide wählen vorab erwünschte Aufgaben, Tonfall, Kleidung, Dauer und Tabus. Haushalt, Getränke, Körperpflege oder erotische Dienste sind getrennte Kategorien. Zustimmung in einer Kategorie öffnet nicht automatisch die nächste.'],['Befehle und Kontrolle','Anweisungen bleiben im vereinbarten Rahmen und müssen sicher ausführbar sein. Erniedrigende Sprache, Öffentlichkeit, Geld oder Schlafentzug brauchen eigene Grenzen und besondere Vorsicht. Ein Stoppwort beendet auch einen königlichen Befehl.'],['Verantwortung der Führung','Die führende Person achtet auf Erschöpfung, Gesundheit und emotionale Reaktionen. Macht wird nicht genutzt, um Abhängigkeit, Angst oder reale Nachteile zu erzeugen. Wer Verantwortung nur tragen möchte, solange das Tablett glänzt, ist noch kein Hofmeister.'],['Dienstschluss','Das Ende wird klar ausgesprochen, Rollen und Titel werden abgelegt. Rückmeldung und Nachsorge gelten für beide Seiten. Aufgaben, die außerhalb einer Szene weiterlaufen sollen, werden regelmäßig überprüft und können jederzeit neu verhandelt werden.']]},
 royalKnots:{kicker:'BDSM · Königliche Knotenwerkstatt',title:'Bannbänder ohne Kerkermeister-Diplom',intro:'Seide, Manschetten und ein sauber gelegter Knoten können aufregend aussehen. Sicher werden sie erst durch passende Ausrüstung, schnelle Befreiung und ständige Aufmerksamkeit.',sections:[['Passform','Manschetten liegen flach an und drücken Nerven oder Durchblutung nicht ab. Hautfarbe, Wärme, Bewegung und Gefühl werden regelmäßig kontrolliert. Taubheit, Kribbeln, starke Schmerzen oder Verfärbung bedeuten sofortiges Lösen.'],['Knoten und Position','Knoten liegen nicht direkt auf empfindlichen Nerven, Gelenken oder dem Hals. Positionen dürfen Atmung und Gleichgewicht nicht gefährden. Anfänger verzichten auf Aufhängungen und lernen zunächst bei qualifizierten, erfahrenen Personen.'],['Schneller Ausgang','Sicherheitsschere, Schlüssel und ein klarer Lösungsplan liegen in Reichweite. Eine gefesselte Person bleibt niemals allein. Das gilt auch, wenn angeblich nur kurz ein Drache vor dem Tor unterschreiben muss.'],['Materialpflege','Seile und Manschetten werden auf Verschleiß, scharfe Kanten und Verschmutzung geprüft. Reinigung richtet sich nach dem Material; poröse Ausrüstung wird nicht unbedacht geteilt. Nach dem Spiel werden Druckstellen und Beweglichkeit kontrolliert.']]}
});
const newestPosts=[
 {key:'bedchamberPact',title:'Der Schlafgemach-Pakt in dreifacher Ausfertigung',time:'Ganz neu · Sex & Etikette',copy:'Noch bevor die Roben fallen könnten, werden Wünsche, Schutz und Privatsphäre besprochen. Romantik ohne Pergamentkrieg – aber mit einem klaren Ja, denn selbst Liebeszauber besitzen keine Generallizenz.',src:'assets/schlafgemach-pakt.png',alt:'Erwachsenes Zauberpaar bespricht vor einem mittelalterlichen Schlafgemach ein Pergament'},
 {key:'castlePetplay',title:'Wer ist ein braver Schlosswolf?',time:'Ganz neu · Petplay',copy:'Ohren auf, Alltag aus: Beim erwachsenen Petplay darf gebellt, geschnurrt und königlich gelobt werden. Der Schlosswolf bleibt trotzdem ein Mensch mit Grenzen – und die Leckerlibörse enthält bitte keine echten Hundekekse.',src:'assets/petplay-schlosswolf.png',alt:'Zwei erwachsene Fantasy-Gäste bei einem humorvollen Schlosswolf-Rollenspiel'},
 {key:'serviceRoles',title:'Der Tablettzauber der gehobenen Dienerschaft',time:'Ganz neu · Dienst & Führung',copy:'Ein tiefer Blick, ein silbernes Tablett und die Frage, welcher Wunsch heute erfüllt werden darf. Gute Führung kommandiert nicht blind; sie kennt Auftrag, Grenze und den exakten Zeitpunkt des Dienstschlusses.',src:'assets/dienst-und-fuehrung.png',alt:'Erwachsene Zauberin auf einem Thron und erwachsener Zauberer mit Tablett'},
 {key:'royalKnots',title:'Knoten, Schlüssel und der beleidigte Burggeist',time:'Ganz neu · Bannbandkunde',copy:'Weiche Bänder, offene Manschetten und eine Sicherheitsschere: Die königliche Knotenwerkstatt weiß, dass schnelle Befreiung reizvoller ist als ein peinlicher Besuch der Burgfeuerwehr.',src:'assets/koenigliche-knotenwerkstatt.png',alt:'Manschetten, Seil, Bänder, Schlüssel und Sicherheitsschere auf einem mittelalterlichen Tisch'}
];
newestFeed.insertAdjacentHTML('afterbegin',newestPosts.map(item=>`<article class="post newest-fantasy-post"><header class="post-head"><div class="post-avatar newest-avatar">✦</div><div><b>Only Wizzard · Nachtakademie <span class="verified">✓</span></b><span>${item.time}</span></div><button>•••</button></header><div class="post-copy"><p><b>${item.title}:</b> ${item.copy}</p></div><img class="newest-photo" src="${item.src}" alt="${item.alt}" loading="lazy"><div class="newest-note">18+ · freiwillig · humorvoll, aber nicht leichtsinnig</div><button class="read-article newest-read" data-article="${item.key}">VOLLARTIKEL AUS DEM ARCHIV HOLEN <span>→</span></button><footer class="post-actions"><button class="like">♡ <span>372</span></button><button>○ <span>89</span></button><button>↗</button><button class="bookmark">⌑</button></footer></article>`).join(''));
document.querySelectorAll('.newest-read').forEach(button=>button.addEventListener('click',()=>openArticle(button.dataset.article)));
document.querySelectorAll('.newest-fantasy-post .like').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('liked');button.firstChild.textContent=button.classList.contains('liked')?'♥ ':'♡ ';const count=button.querySelector('span');count.textContent=Number(count.textContent)+(button.classList.contains('liked')?1:-1)}));

