articles.material={kicker:'Materialkunde · Vergleich',title:'Was ist besser: Lack oder Leder?',intro:'Glanz oder Charakter? Beide Materialien sprechen eine eigene magische Sprache – entscheidend sind Gefühl, Anlass und die richtige Pflege.',sections:[['Lack: die dramatische Wahl','Die hochglänzende Oberfläche reflektiert jedes Kerzenlicht und wirkt sofort theatralisch. Sie ist weniger nachgiebig, reagiert stärker auf Wärme und möchte ohne scharfe Knicke gelagert werden.'],['Leder: warm und wandelbar','Feines Leder passt sich mit der Zeit an und entwickelt eine persönliche Patina. Es wirkt zurückhaltender, riecht charakteristisch und braucht regelmäßige, sparsame Pflege.'],['Was fühlt sich richtig an?','Wer eine klare, kühle Oberfläche und auffälligen Glanz mag, greift eher zu Lack. Wer Wärme, Struktur und ein Material bevorzugt, das mit der Zeit weicher wird, wählt Leder.'],['Die Anprobe','Neue Roben werden zunächst kurz und ohne anspruchsvolle Rituale getragen. Bewegungsfreiheit, Temperatur und Hautgefühl entscheiden – nicht allein der Blick in den Spiegel.']]};
articles.care={kicker:'Werkstatt · Materialpflege',title:'Glanz bewahren, Geschmeidigkeit erhalten',intro:'Besondere Gewänder verlangen Aufmerksamkeit. Mit wenigen ruhigen Handgriffen bleiben Lack und Leder lange bereit für den nächsten Auftritt.',sections:[['Lack reinigen','Staub mit einem weichen, leicht feuchten Tuch abnehmen. Keine aggressiven Mittel, Öle oder rauen Schwämme verwenden; sie können den Glanz dauerhaft trüben.'],['Leder nähren','Zuerst an einer unauffälligen Stelle testen. Eine kleine Menge geeigneter Pflege dünn einarbeiten, einziehen lassen und anschließend sanft nachpolieren.'],['Richtig lagern','Beide Materialien trocken, dunkel und mit Luft dazwischen aufbewahren. Lack darf nicht dauerhaft auf Lack liegen, Leder nicht direkt an einer Wärmequelle.'],['Nach dem Tragen','Gewänder vollständig auslüften lassen, bevor sie in den Schrank zurückkehren. Nähte und Verschlüsse prüfen und kleine Schäden früh versorgen.']]};
articles.knots={kicker:'Knotenkunde · Orientierung',title:'Welcher magische Knoten passt zu mir?',intro:'Der schönste Knoten ist nicht der komplizierteste, sondern derjenige, dessen Zweck, Belastung und Lösung alle Beteiligten verstehen.',sections:[['Der dekorative Mondknoten','Locker, symmetrisch und schnell wieder geöffnet. Ideal zum Kennenlernen von Material und Fingertechnik – zunächst immer nur auf dem Tisch üben.'],['Die Sternenschlaufe','Eine verstellbare Schlaufe für Requisiten und Gewänder. Sie darf nie an Hals, Gelenken oder Stellen verwendet werden, an denen Druck oder Durchblutung problematisch werden können.'],['Das Runengeflecht','Mehrere Stränge ergeben ein optisch aufwendiges Muster. Es verlangt Geduld, klare Kommunikation und regelmäßige Kontrolle, ob alles bequem bleibt.'],['Schnelle Lösung','Jeder Knoten braucht einen bekannten Lösungsweg. Sicherheitswerkzeug bleibt griffbereit; Taubheit, Schmerz, Atemprobleme oder ein Stoppsignal beenden das Ritual sofort.']]};
const moreFeed=document.querySelector('.content');
const newPosts=[
{key:'material',time:'Neu · Materialkunde',title:'Was ist besser: Lack oder Leder?',copy:'Glänzend und dramatisch oder warm und geschmeidig? Wir vergleichen Wirkung, Tragegefühl und die kleinen Eigenheiten beider magischen Materialien.',image:'assets/lack-oder-leder.png',alt:'Zwei erwachsene Zauberer vergleichen glänzende und matte schwarze Gewänder'},
{key:'care',time:'Neu · Zauberwerkstatt',title:'Damit der Glanz nicht vergeht',copy:'Pflegen, polieren, richtig lagern: So bleiben besondere Roben geschmeidig und bereit für lange Nächte im Salon.',image:'assets/materialpflege.png',alt:'Pflegeset für glänzende und lederartige magische Stoffe'},
{key:'knots',time:'Neu · Knotenkunde',title:'Welcher Knoten passt zu mir?',copy:'Mondknoten, Sternenschlaufe oder Runengeflecht? Ein Einstieg in dekorative Muster, sichere Anwendung und schnelle Lösungen.',image:'assets/magische-knoten.png',alt:'Erwachsene Magierin übt dekorative Knoten an einem Arbeitstisch'}
];
newPosts.forEach(post=>{moreFeed.insertAdjacentHTML('beforeend',`<article class="post"><header class="post-head"><div class="post-avatar">OW</div><div><b>Only Wizzard <span class="verified">✓</span></b><span>${post.time}</span></div></header><div class="post-copy"><p><b>${post.title}</b> ${post.copy}</p></div><div class="article-photo"><img src="${post.image}" alt="${post.alt}"><div><span>NEUE LEKTION</span><h2>${post.title}</h2></div></div><button class="read-article more-read">VOLLSTÄNDIGEN ARTIKEL LESEN <span>→</span></button><footer class="post-actions"><button class="like">♡ <span>186</span></button><button>○ <span>37</span></button><button>↗</button><button class="bookmark">⌑</button></footer></article>`);const card=moreFeed.lastElementChild;card.querySelector('.more-read').addEventListener('click',()=>openArticle(post.key));card.querySelector('.like').addEventListener('click',e=>{const b=e.currentTarget;b.classList.toggle('liked');b.firstChild.textContent=b.classList.contains('liked')?'♥ ':'♡ ';const n=b.querySelector('span');n.textContent=Number(n.textContent)+(b.classList.contains('liked')?1:-1)})});
