document.getElementById('year').textContent=new Date().getFullYear();
const toast=document.getElementById('toast');
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
document.getElementById('subscribe-button').addEventListener('click',e=>{e.currentTarget.querySelector('span').textContent='ABONNIERT ✓';e.currentTarget.disabled=true;showToast('Willkommen im Salon! ✦')});
document.querySelectorAll('.like').forEach(button=>button.addEventListener('click',()=>{button.classList.toggle('liked');button.firstChild.textContent=button.classList.contains('liked')?'♥ ':'♡ ';const count=button.querySelector('span');count.textContent=Number(count.textContent)+(button.classList.contains('liked')?1:-1)}));
document.getElementById('newsletter-form').addEventListener('submit',e=>{e.preventDefault();document.getElementById('form-note').textContent='Depesche bestellt! ✦';e.currentTarget.reset();showToast('Deine geheime Depesche ist unterwegs.')});

const articles={
wand:{kicker:'Stabkunde · Lektion 07',title:'Länge, Umfang und der richtige Griff',intro:'Zauberstäbe sind so verschieden wie ihre Besitzer. Doch was zählt wirklich, wenn ein Stab seine volle Wirkung entfalten soll?',sections:[['Die Länge','Kurze Modelle reagieren schnell und präzise, längere erzeugen einen größeren Bewegungsradius. Wichtig ist, dass die Spitze kontrollierbar bleibt und der Stab zur Reichweite seines Zaubernden passt.'],['Umfang und Härtegrad','Ein kräftiger Umfang vermittelt Präsenz, verlangt aber eine sichere Hand. Nachgiebige Hölzer verzeihen kleine Fehler; starre Modelle übertragen dagegen jede Bewegung unmittelbar.'],['Der Griff','Nicht würgen – führen. Die Hand beginnt locker, wird im entscheidenden Moment fester und lässt danach wieder nach. Wer nur Kraft einsetzt, ermüdet schneller als jemand mit Gefühl für Rhythmus.'],['Pflege danach','Nach jeder intensiven Anwendung wird der Stab sanft gereinigt, auf Risse geprüft und trocken gelagert. Ein Tropfen geeignetes Holzöl erhält Glanz und Geschmeidigkeit.']]},
ribbons:{kicker:'Abendkurs · Fortgeschrittene Magie',title:'Bänder, Bannkreise und Vertrauen',intro:'Verzauberte Bänder können ein aufregendes Ritual schaffen – sofern alle Beteiligten den Ablauf freiwillig wählen und jederzeit beenden können.',sections:[['Vor dem Ritual','Zaubernde besprechen Wünsche, Grenzen und empfindliche Stellen. Ein eindeutiges Lösungswort beendet den Bann sofort; ein zweites Signal kann bedeuten, dass Intensität oder Position verändert werden sollen.'],['Sichere Bannkreise','Bänder bleiben so locker, dass Atmung und Durchblutung frei sind. Hals, Gelenke und Nervenbahnen werden nicht belastet. Scheren oder ein schneller Lösungszauber liegen griffbereit.'],['Führung und Hingabe','Eine Person kann die Richtung des Rituals vorgeben, während die andere freiwillig Kontrolle abgibt. Diese Rollen gelten nur für den vereinbarten Zeitraum und können jederzeit neu verhandelt werden.'],['Nach dem Bann','Wärme, Wasser oder Zaubertrank und ein ruhiges Gespräch helfen beim Zurückkehren in den Alltag. Beide sagen offen, was schön war und was beim nächsten Mal anders sein soll.']]},
academy:{kicker:'Akademie-Etikette',title:'Meister, Lehrling und freiwilliger Gehorsam',intro:'Eine spannende Prüfung entsteht nicht durch Zwang, sondern durch bewusst gewählte Rollen, Vertrauen und die Freiheit, jederzeit auszusteigen.',sections:[['Rollen wählen','Meister und Lehrling legen gemeinsam fest, welche Anweisungen zum Spiel gehören. Titel, Tonfall und Aufgaben werden vorher vereinbart – außerhalb des Rituals begegnen sich beide auf Augenhöhe.'],['Prüfungen und Konsequenzen','Aufgaben dürfen herausfordern, aber niemals vereinbarte Grenzen überschreiten. Spielerische Konsequenzen werden vorab besprochen und dienen dem gemeinsamen Erlebnis, nicht echter Bestrafung.'],['Das Lösungswort','Ein klares Wort oder Handzeichen stoppt jede Prüfung ohne Diskussion. Es ist kein Scheitern, sondern ein Werkzeug guter Zauberkunst. Regelmäßiges Nachfragen schafft zusätzliche Sicherheit.'],['Die Rückkehr','Nach intensiven Rollen wird das Ritual ausdrücklich beendet. Lob, Ruhe und ein Gespräch darüber, wie es beiden geht, gehören zur hohen Schule der Magie.']]},
stamina:{kicker:'Gerätekunde · Werkstattnotizen',title:'Politur, Griff und magische Ausdauer',intro:'Nicht jeder Zauber gelingt beim ersten Schwung. Gute Technik, Pausen und eine gepflegte Ausrüstung helfen mehr als hektischer Ehrgeiz.',sections:[['Richtig polieren','Ein weiches Tuch und wenige kreisende Bewegungen genügen. Zu viel Reibung kann empfindliche Oberflächen erhitzen oder stumpf machen.'],['Rhythmus vor Tempo','Ruhige, gleichmäßige Bewegungen sparen Kraft. Wer merkt, dass die Konzentration nachlässt, verlangsamt den Takt oder legt eine kurze Pause ein.'],['Wenn Magie zu früh entweicht','Aufregung gehört dazu. Statt sich zu schämen, können Zaubernde atmen, lachen und später einen neuen Versuch beginnen. Ein gelungenes Ritual wird nicht an Minuten gemessen.'],['Kleine Stäbe, große Wirkung','Präzision und Aufmerksamkeit sind wichtiger als beeindruckende Maße. Der beste Stab ist derjenige, mit dem alle Beteiligten sich sicher und wohl fühlen.']]}
};
const modal=document.createElement('div');modal.className='article-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="modal-backdrop"></div><article class="modal-panel" role="dialog" aria-modal="true" aria-labelledby="article-title"><button class="modal-close" aria-label="Artikel schließen">×</button><div class="modal-content"></div></article>';document.body.appendChild(modal);
function openArticle(key){const a=articles[key];modal.querySelector('.modal-content').innerHTML=`<p class="article-kicker">${a.kicker}</p><h2 id="article-title">${a.title}</h2><p class="article-intro">${a.intro}</p>${a.sections.map(([h,t])=>`<section><h3>${h}</h3><p>${t}</p></section>`).join('')}<aside class="consent-note"><b>Goldene Zauberregel</b><br>Alle beschriebenen Rituale richten sich ausschließlich an Erwachsene und setzen freiwillige, informierte Zustimmung voraus.</aside>`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modal.querySelector('.modal-close').focus()}
function closeArticle(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
[['.wand-card','wand'],['.ribbon-card','ribbons'],['.rules-card','academy'],['.topic-grid','stamina']].forEach(([selector,key])=>{const card=document.querySelector(selector);if(!card)return;const button=document.createElement('button');button.className='read-article';button.innerHTML='VOLLSTÄNDIGEN ARTIKEL LESEN <span>→</span>';button.addEventListener('click',()=>openArticle(key));card.insertAdjacentElement('afterend',button)});
modal.querySelector('.modal-close').addEventListener('click',closeArticle);modal.querySelector('.modal-backdrop').addEventListener('click',closeArticle);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeArticle()});
